#lang info
(define name "rdf-dc")
(define deps '("base" "rdf-core"))
(define build-deps '("scribble-lib" "sandbox-lib" "racket-doc"))
(define scribblings '(("scribblings/rdf-dc.scrbl" (multi-page) (library))))
(define test-omit-paths '("scribblings"))
(define pkg-desc "RDF vocabularies for Dublin Core specifications.")
(define version "0.1.1")
(define pkg-authors '(johnstonskj))
(define license 'Apache-2.0)
